language: node_js
node_js:
  - "8"
before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      npm install codecov
      npm run cover
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
